salesassistant/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace salesassistant.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

salesassistant/Pages/AddEntry.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using salesassistant.Database;
using salesassistant.Model;

namespace salesassistant.Pages
{
	[Authorize(Roles = "Admin")]
    public class AddEntryModel : PageModel
    {
		[BindProperty]
        public IFormFile FileUpload { get; set; }

		public List<ExCo> ExCos { get; set; }

		[BindProperty]
		public Product Product { get; set; }

		[BindProperty]
        public Uri ImageUri { get; private set; }

		public List<string> ExcoOptions { get; set; }

		public string ServiceName { get; set; }

        public void OnGet(string key = "", string service_name = "")
        {
			if (!"".Equals(service_name))
			{
				ServiceName = service_name;
			}
			SalesAssistantContext context = HttpContext.RequestServices.GetService(typeof(SalesAssistantContext)) as SalesAssistantContext;
			if (!"".Equals(key))
			{
				ImageUri = context.GetBlobURI(key);
			}
			ExcoOptions = new List<string>();
			ExCos = context.GetExCos();
			ExCos.ForEach((ExCo obj) =>
			{
				ExcoOptions.Add(obj.Name);
			});
        }

		public async Task<IActionResult> OnPostAsync()
        {
            System.Diagnostics.Debug.WriteLine("adding new record");
			SalesAssistantContext context = HttpContext.RequestServices.GetService(typeof(SalesAssistantContext)) as SalesAssistantContext;
            if (!ModelState.IsValid)
            {
                return Page();
            }

			//context.AddMessage(Message.MessageText, Message.Name, DateTime.Now.ToShortDateString());
			if (ImageUri != null) 
			{
				Product.ImageUri = ImageUri;
			}
			context.AddProduct(Product);
			return RedirectToPage("/AddEntry", new { service_name = Product.ServiceName });
        }

		public async Task<IActionResult> OnPostUploadImageAsync()
        {
            System.Diagnostics.Debug.WriteLine("Uploading image : " + FileUpload.FileName);
			SalesAssistantContext context = HttpContext.RequestServices.GetService(typeof(SalesAssistantContext)) as SalesAssistantContext;
            await context.UploadAsync(FileUpload);
			return RedirectToPage("/AddEntry", new { key = FileUpload.FileName });
        }
    }
}

salesassistant/Pages/COE.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using salesassistant.Database;
using salesassistant.Model;

namespace salesassistant.Pages
{
    public class COEModel : PageModel
    {
		public static string Key { get; set; }
		public CoE coe { get; set; }
		public List<SalesDocument> salesDocuments { get; set; }

		[BindProperty]
        public IFormFile FileUpload { get; set; }

        public void OnGet(string key)
        {
			Key = key;

			SalesAssistantContext context = HttpContext.RequestServices.GetService(typeof(SalesAssistantContext)) as SalesAssistantContext;
			coe = context.GetCoE(key);
			coe.productList = context.GetProducts(coe.Name);

			salesDocuments = context.GetFiles(key).Result;
        }

		public async Task<IActionResult> OnPostUploadDocumentAsync()
        {
            SalesAssistantContext context = HttpContext.RequestServices.GetService(typeof(SalesAssistantContext)) as SalesAssistantContext;
            await context.UploadDocumentAsync(FileUpload, Key);
            return RedirectToPage("/COE", new { key = Key });
        }
    }
}

salesassistant/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace salesassistant.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

salesassistant/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace salesassistant.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }

	    }
}

salesassistant/Pages/Exco.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.WindowsAzure.Storage.File;
using salesassistant.Database;
using salesassistant.Model;

namespace salesassistant.Pages
{
    public class ExcoModel : PageModel
    {

		public static string Key { get; set; }

		public ExCo Exco { get; set; }

		bool isAuthenticated { get; }

		public List<SalesDocument> salesDocuments { get; set; }

		[BindProperty]
        public IFormFile FileUpload { get; set; }

        [Authorize]
        public void OnGet(string key)
        {
			Key = key;

			SalesAssistantContext context = HttpContext.RequestServices.GetService(typeof(SalesAssistantContext)) as SalesAssistantContext;
			Exco = context.GetExCo(key);
			Exco.coeList = context.GetCoEs(Exco.Name);
            
			salesDocuments = context.GetFiles(key).Result;
			// Getting User Identity: Authentication etc...
			// User.Identity.Name;
		}

		public async Task<IActionResult> OnPostUploadDocumentAsync()
        {
			SalesAssistantContext context = HttpContext.RequestServices.GetService(typeof(SalesAssistantContext)) as SalesAssistantContext;
			await context.UploadDocumentAsync(FileUpload, Key);
			return RedirectToPage("/Exco", new { key = Key });
        }
    }
}

salesassistant/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using salesassistant.Database;
using salesassistant.Model;

namespace salesassistant.Pages
{
	
    public class IndexModel : PageModel
    {
		public String Name { get; set; }
        public String Description { get; set; }
        public List<ExCo> excoList { get; set; }

        public void OnGet()
        {
            SalesAssistantContext context = HttpContext.RequestServices.GetService(typeof(SalesAssistantContext)) as SalesAssistantContext;
            excoList = context.GetExCos();
        }


    }
}

salesassistant/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using salesassistant.Database;
using salesassistant.Model;

namespace salesassistant.Pages
{
    public class LoginModel : PageModel
    {
		//public LoginModel(UserManager userManager)
		public LoginModel() {
			//this._userManager = userManager;
		}

		//UserManager _userManager;


		[BindProperty]
		public string Username { get; set; }

		[BindProperty]
		public string Password { get; set; }

		[AllowAnonymous]
		public void OnGet()
        {
        }

		public IActionResult OnPostUserLogin()
        {
            SalesAssistantContext context = HttpContext.RequestServices.GetService(typeof(SalesAssistantContext)) as SalesAssistantContext;
		    //User user = context.GetUserPassword(Username, Password);

			//if (user != null) {
			context.SignIn(HttpContext, new User
			{
				Email = Username,
				Password = Password
			});
			return RedirectToPage("/index");
			//} else {
			//	return RedirectToPage("/login", new { login = "failed"});
			//}
        }
    }
}

salesassistant/Pages/PasswordReset.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using salesassistant.Database;
using salesassistant.Model;

namespace salesassistant.Pages
{
    public class PasswordResetModel : PageModel
    {
		public static string UserEmail { get; set; }
		[BindProperty]
		public string NewPassword { get; set; }

		public void OnGet(string useremail)
        {
		    UserEmail = useremail;
        }
        
		public IActionResult OnPostResetPassword()
        {
            SalesAssistantContext context = HttpContext.RequestServices.GetService(typeof(SalesAssistantContext)) as SalesAssistantContext;
            var Users = context.GetUsers();
			User toggledUser = Users.Find(user => user.Email.Equals(UserEmail));
			toggledUser.Password = NewPassword;
			context.UpdateUserPassword(toggledUser);
            return RedirectToPage("/Users");
        }
    }
}

salesassistant/Pages/Product.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using salesassistant.Database;
using salesassistant.Model;

namespace salesassistant.Pages
{
	public class ProductModel : PageModel
	{
        
		public static string Key { get;set; }
		public Product product { get; set; }
		public List<SalesDocument> presentationDocuments { get; set; }
		public List<SalesDocument> questionnaireDocuments { get; set; }
		public List<SalesDocument> pricingDocuments { get; set; }
		public List<SalesDocument> brochureDocuments { get; set; }


		[BindProperty]
        public IFormFile FileUpload { get; set; }

		[BindProperty]
		public string FileCategory { get; set; }

        public void OnGet(string key)
        {
			Key = key;
			SalesAssistantContext context = HttpContext.RequestServices.GetService(typeof(SalesAssistantContext)) as SalesAssistantContext;
			product = context.GetProduct(key);

			presentationDocuments = context.GetProductFiles(key, "Presentations").Result;
			questionnaireDocuments = context.GetProductFiles(key, "Questionnaire").Result;
			pricingDocuments = context.GetProductFiles(key, "Pricing").Result;
			brochureDocuments = context.GetProductFiles(key, "Brochure").Result;
        }

		public async Task<IActionResult> OnPostUploadDocumentAsync()
        {
			if (FileUpload == null || FileCategory == null) {
				return RedirectToPage("/Product", new { key = Key });
			}
            SalesAssistantContext context = HttpContext.RequestServices.GetService(typeof(SalesAssistantContext)) as SalesAssistantContext;
			await context.UploadProductDocumentAsync(FileUpload, Key, FileCategory);
            return RedirectToPage("/Product", new { key = Key });
        }
    }
}

salesassistant/Pages/Tables.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using salesassistant.Database;
using salesassistant.Model;

namespace salesassistant.Pages
{
    public class TablesModel : PageModel
    {
        
		public string currentExco { get; set; }
		public List<CoE> coes = new List<CoE>();
		public List<ExCo> excos = new List<ExCo>();
		public List<Product> products = new List<Product>();

		public string GetActiveTab(string tabName)
		{
			if (tabName.Equals(currentExco)) return "active";
			return "";
		}

        public void OnGet(string exco = "Chief Digital Officer")
        {
			SalesAssistantContext context = HttpContext.RequestServices.GetService(typeof(SalesAssistantContext)) as SalesAssistantContext;
			excos = context.GetExCos();
			currentExco = exco;

			coes = context.GetCoEs(currentExco);
			coes.OrderBy(coe => coe.Name);
			    
			products = context.GetProductsInExco(currentExco);
        }

        public List<Product> GetProductsForCoE(string COEName)
		{
			return products.FindAll(product => product.COEName.ToLower().Equals(COEName.ToLower()));
		}
    }
}

salesassistant/Pages/Users.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using salesassistant.Database;
using salesassistant.Model;

namespace salesassistant.Pages
{
	[Authorize(Roles = "Admin")]
    public class UsersModel : PageModel
    {
		public List<User> Users { get; set; }
		[BindProperty]
		public string NewUserEmail { get; set; }
		[BindProperty]
        public string NewUserPassword { get; set; }
		[BindProperty]
        public string ChangedPassword { get; set; }
		[BindProperty]
		public Boolean NewUserAccess { get; set; }

        public void OnGet()
        {
			SalesAssistantContext context = HttpContext.RequestServices.GetService(typeof(SalesAssistantContext)) as SalesAssistantContext;
			this.Users = context.GetUsers();
        }

		public IActionResult OnPostToggleUser(string email)
		{
			SalesAssistantContext context = HttpContext.RequestServices.GetService(typeof(SalesAssistantContext)) as SalesAssistantContext;
			this.Users = context.GetUsers();
			User toggledUser = Users.Find(user => user.Email.Equals(email));
            toggledUser.Access = !toggledUser.Access;
			context.UpdateUsers(this.Users);
			return RedirectToPage("/Users");
		}

		public IActionResult OnPostDeleteUser(string email)
        {
            SalesAssistantContext context = HttpContext.RequestServices.GetService(typeof(SalesAssistantContext)) as SalesAssistantContext;
            this.Users = context.GetUsers();
			User userToDelete = Users.Find(user => user.Email.Equals(email));
            context.DeleteUser(userToDelete);
            return RedirectToPage("/Users");
        }
        
		public IActionResult OnPostResetPassword(string email) {
			return RedirectToPage("/PasswordReset", new { useremail = email});
		}
        
        public IActionResult OnPostSaveNewUser()
		{
			User user = new User()
			{
				Email = NewUserEmail,
				Password = NewUserPassword,
				Access = NewUserAccess
			};
			SalesAssistantContext context = HttpContext.RequestServices.GetService(typeof(SalesAssistantContext)) as SalesAssistantContext;
			context.SaveUser(user);
			return RedirectToPage("/Users");
		}
    }
}

salesassistant/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

salesassistant/Pages/AddEntry.cshtml
@page
@model AddEntryModel
@{
    ViewData["Title"] = "Add Entry";
}

<div class="container-fluid white">
    @if (Model.ServiceName != null)
    {
        <div class="row introduction text-center ">
            <div class="alert alert-success alert-dismissible" role="alert" style="width:100%">
                @Model.ServiceName added successfully
            </div>
        </div>
    }
    <form method="POST">
        <!-- COE NAME -->
        <div class="row introduction white">
            @if (Model.ImageUri != null)
            {
                <div data-toggle="modal" data-target="#myModal" class="col-md-2 click"><img src="@Model.ImageUri" alt=""/></div>
            }
            else
            {
                <div data-toggle="modal" data-target="#myModal" class="col-md-2 click"><img src="images/placeholder.svg" alt="" /></div>
            }
            <div class="col-md-10">
                <div class="coe_name">
                    <select asp-for="Product.ExcoName">
                        <option disabled selected>Choose One</option>
                        @foreach (var name in @Model.ExcoOptions)
                        {
                            <option>@name</option>
                        }
                    </select>
                </div>
                <div class="coe_name">
                    <input asp-for="Product.COEName" maxlength="20" placeholder="Division Name">
                </div>
                <div class="solution_name">
                    <span>
                        <input asp-for="Product.ServiceName" maxlength="30" placeholder="Service Name">
                    </span>
                </div>
                <div class="owner_name col-md-4 float-left">
                    <input asp-for="Product.OwnerOneName" maxlength="20" placeholder="Owner Name">
                    <input asp-for="Product.OwnerOneEmail" type="email" maxlength="30" placeholder="Email">
                    <input asp-for="Product.OwnerOneNumber" type="tel" maxlength="10" placeholder="Cell Phone">
                </div>
                <div class="owner_name col-md-4 float-left">
                    <input asp-for="Product.OwnerTwoName" maxlength="20" placeholder="Owner Name">
                    <input asp-for="Product.OwnerTwoEmail" type="email" maxlength="30" placeholder="Email">
                    <input asp-for="Product.OwnerTwoNumber" type="tel" maxlength="10" placeholder="Cell Phone">
                </div>

                @*<div class="owner_name col-md-4 float-left">
                    <textarea rows="4" maxlength="30" placeholder="Keywords for search"></textarea>
                </div>*@
            </div>
        </div>

        <!-- Target Audience + ELEVATOR PITCH SERVICE OFFERING DESCRIPTION -->
        <div class="row">
            <div class="col-md-4 dark_grey">
                <div class="block_headings col-md-12" style="color: white">
                    <span>ELEVATOR PITCH</span> <span>
                        <textarea asp-for="Product.ElevatorPitch" rows="5" maxlength="380"></textarea>
                    </span>
                </div>
            </div>
            <div class="col-md-8 dark_grey_1">
                <div class="block_headings col-md-12" style="color: white">
                    <span>SERVICE OFFERING DESCRIPTION</span> <span class="full_description">
                        <textarea asp-for="Product.ServiceOfferingDescription" rows="5" maxlength="620"></textarea>
                    </span>
                </div>
            </div>
        </div>

        <!-- VALUE PROPOSITION + PROBLEM -->
        <div class="row white page_break">
            <div class="col-md-4 border-right">
                <div class="block_headings col-md-12" style="color: grey">
                    <span>PROBLEM SOLVED</span><span>
                        <textarea asp-for="Product.ProblemSolved" rows="5" maxlength="870"></textarea>
                    </span>
                </div>
            </div>
            <div class="col-md-8">
                <div class="block_headings col-md-12 val_prop" style="color:grey">
                    <span>VALUE PROPOSITION</span> <span class="full_description">
                        <textarea asp-for="Product.ValueProposition" rows="5" maxlength="2000"></textarea>
                    </span>
                </div>
            </div>
        </div>

        <!-- FEATURES + COMMERCIALS -->
        <div class="row white">
            <div class="col-md-12">
                <div class="block_headings col-md-12 val_prop" style="color:grey">
                    <span>Customers and projects</span> <span class="full_description">
                        <textarea asp-for="Product.CustomersAndProjects" rows="5" maxlength="2500"></textarea>
                    </span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="block_headings col-md-12 val_prop" style="color:grey">
                    <span>Services</span> <span class="full_description">
                        <textarea asp-for="Product.Services" rows="5" maxlength="2500"></textarea>
                    </span>
                </div>
            </div>
        </div>

        <!-- FOOTER -->
        <div class="row footer">
            <div class="col-md-12">
                Version: 1
                <br />
                <input asp-for="Product.Submitter" maxlength="20" placeholder="Name and Surname">

                <button type="submit" class="submit float-right btn btn-danger">SUBMIT</button>
            </div>
        </div>
    </form>
</div>

<!-- The Modal -->
<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Upload Image</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <form method="post" enctype="multipart/form-data">
                <!-- Modal body -->
                <div class="modal-body">
                    <input required accept="image/*" asp-for="FileUpload" type="file">
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    @*<button type="button" class="btn btn-danger">Submit</button>*@
                    <input class="col-md-6" type="submit" value="Upload" id="uploader" asp-page-handler="UploadImage" />
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>

            </form>
        </div>
    </div>
</div>

salesassistant/Pages/COE.cshtml
@page
@model COEModel
@{
}
<!-- MAIN CONTAINER -->
<div class="container-fluid">
    <!-- COE NAME -->
    <div class="row introduction white">
        <div class="col-lg-2 col-md-2 col-xs-2">
        @if (Model.coe.ImageUri == null)
        {
            <img class="img-fluid max-width" src = "images/bar-code-01.svg" alt="" />
        }
        else
        {
            <img class="img-fluid max-width" src = "@Model.coe.ImageUri" alt="" />
        }
        </div>
        <div class="col-lg-10 col-md-10 col-xs-10" style="margin-top: auto; margin-bottom: auto;">
            <div class="solution_name"><span>@Model.coe.Name</span></div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 col-xs-12 col-md-12 dark_grey_1">
            <div class="block_headings col-md-12" style="color: white">
                <span>@Model.coe.Name DESCRIPTION</span> 
                @{ 
                    List<string> descriptionParts = Model.coe.Description.Split(";").OfType<string>().ToList();
                }
                @*<span class="full_description">*@ 
                <ul class=full_description>
                    @foreach(var part in descriptionParts)
                    {
                        <li>@part</li>
                    }
                </ul>
                @*</span>*@ 
            </div>
        </div>
    </div>
    <div class="row white_0">
        <!-- Tabs -->
        <div class="col-md-6">
            <ul class="nav nav-tabs 123" id="navbartabs" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" role="tab" href="#details" id="details-tab">Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" role="tab" href="#documents" id="documents-tab">Documents</a>
                </li>
            </ul>
        </div>
        <div class="col-md-6">
            <div class="float-right">
                <button class="btn btn-primary" data-toggle="modal" data-target="#uploadDocument">
                    Upload Document
                </button>
            </div>
        </div>
    </div>
    <div class="tab-content white_0" id="tab-content">
        <div class="tab-pane fade show active" id="details" role="tabpanel">
            @if(Model.coe.productList != null)
            {
                @foreach (var product in Model.coe.productList)
                {
                    <div class="col-lg-2 col-md-2 col-xs-2 grid float-left white">
                        <a class="popover_detail" data-trigger="hover" data-placement="bottom" data-content="@product.ServiceName" href="/product?key=@product.ServiceName">
                            @if (product.ImageUri == null)
                            {
                                <img class="img-fluid max-width" src = "images/bar-code-01.svg" alt="" />
                            }
                            else
                            {
                                <img class="img-fluid max-width" src = "@product.ImageUri" alt="" />
                            }
                        </a>
                    </div>
                }
            }
        </div>
       <div class="tab-pane" id="documents" role="tabpanel">
            @foreach(var file in Model.salesDocuments)
            {
                <div class="col-md-2 col-lg-2 col-xs-2 grid float-left white">
                    <a href="@file.downloadLink">
                        <img class="img-fluid text-center max-width pb-2" src="images/icons8-document.svg" alt="" style="display: block; margin: auto;" />
                    </a>
                    <div class="text-center">
                        @file.name
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div id="uploadDocument" class="modal fade" role="dialog">
    <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title text-center">Upload Document</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
            <form action="" method="post" enctype="multipart/form-data">
                <fieldset>
                    <input asp-for="FileUpload" type="file" />
                    <input class="col-md-6" type="submit" value="Upload" id="uploader" asp-page-handler="UploadDocument" />
                </fieldset>
            </form>
        </div>
    </div>
</div>

salesassistant/Pages/Login.cshtml
@page
@model LoginModel
@{
}
<div class="container" style="background: gray;">
    <div class="login-form pt-5 pb-5">
        <div class="main-div">
            <div class="panel">
                <h2>Login</h2>
                <p>Please enter your email and password</p>
            </div>
            <form id="Login" action="" method="post">
                <div class="form-group">
                    <input type="email" class="form-control" id="inputEmail" placeholder="Email Address" asp-for="Username">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" id="inputPassword" placeholder="Password" asp-for="Password">
                </div>
                <button asp-page-handler="UserLogin" type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>
</div>

salesassistant/Pages/Users.cshtml
@page
@model UsersModel
@{
}
<div class="container-fluid white">
    <div class="row">
        <div class="col-md-12">
            <h2>User Access</h2>
            <div class="float-right">
                <button class="btn btn-dark" data-toggle="modal" data-target="#newUser">
                    Add User
                </button>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col"> User Email </th>
                    <th scope="col"> Admin Access </th>
                    <th scope="col"> </th>
                    <th scope="col"> </th>
                    <th scope="col"> </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var user in Model.Users)
                {
                <tr>
                    <td> @user.Email </td>
                    <td> @user.Access</td>
                    <td>
                        <form method="post" asp-page-handler="ToggleUser" asp-route-email="@user.Email">
                            <button class="btn btn-primary">
                                Toggle Admin
                            </button>
                        </form>
                    </td>
                    <td>
                        <form method="post" asp-page-handler="ResetPassword" asp-route-email="@user.Email">
                            <button class="btn btn-primary">Reset Password</button>
                        </form>
                    </td>
                    <td>
                        <form method="post" asp-page-handler="DeleteUser" asp-route-email="@user.Email">
                            <button class="btn btn-danger">Remove</button>
                        </form>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div id="newUser" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title text-center">Add new admin user</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form action="" method="post" enctype="multipart/form-data">
                    <div class="pl-5">
                        <div class="row">
                            <input class="form-control" style="width: 80%" asp-for="NewUserEmail" type="email" placeholder="Email Address" />
                        </div>
                        <div class="row">
                            <input class="form-control" style="width: 80%" asp-for="NewUserPassword" type="password" placeholder="Password" />
                        </div>
                        <div class="row">
                            <input asp-for="NewUserAccess" type="checkbox" /> 
                            <div class="pl-3">Admin access?</div>
                        </div>
                        <div class="row">
                            <input class="col-md-6" type="submit" value="Save" id="saver" asp-page-handler="SaveNewUser" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>